# Generated by Django 5.2 on 2025-05-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scansnapwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='brightness',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='scan',
            name='page_rotate_options',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='scan',
            name='resolution',
            field=models.IntegerField(default=200),
        ),
    ]
