# Generated by Django 5.2 on 2025-05-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scansnapwebapp', '0002_scan_brightness_scan_page_rotate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='paper_height',
            new_name='sheet_height',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='paper_width',
            new_name='sheet_width',
        ),
    ]
