# Generated by Django 5.2 on 2025-05-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scansnapwebapp', '0003_rename_paper_height_scan_sheet_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='page_rotate_options',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
