[project]
name = "scansnap-web"
version = "0.1.0"
description = "ScanSnap web application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "pillow>=11.2.1",
    "ruff>=0.11.7",
]
